//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherEx2.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TGlobalSettings> TGlobalSettings { get; set; }
        public virtual DbSet<TImportedCity> TImportedCity { get; set; }
        public virtual DbSet<TUser2City> TUser2City { get; set; }
        public virtual DbSet<TCurrentWeatherInfo> TCurrentWeatherInfo { get; set; }
        public virtual DbSet<TForecastWeatherInfo> TForecastWeatherInfo { get; set; }
    }
}
