//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherEx2.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCurrentWeatherInfo
    {
        public int Id { get; set; }
        public int CityId { get; set; }
        public string WeatherIcon { get; set; }
        public int WeatherCode { get; set; }
        public string WeatherDescription { get; set; }
        public string StationId { get; set; }
        public System.DateTime CurrentCycleHour { get; set; }
        public System.DateTime LastObservationTime { get; set; }
        public System.DateTime SunriseTime { get; set; }
        public System.DateTime SunsetTime { get; set; }
        public double Temperature { get; set; }
        public double TemperatureFeelsLike { get; set; }
        public double Pressure { get; set; }
        public int LiquidPercipitationRate { get; set; }
        public int UvIndex { get; set; }
        public int RelativeHumidity { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual TImportedCity TImportedCity { get; set; }
    }
}
