//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherEx2.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TForecastWeatherInfo
    {
        public int Id { get; set; }
        public int CityId { get; set; }
        public string WeatherIcon { get; set; }
        public int WeatherCode { get; set; }
        public string WeatherDescription { get; set; }
        public double MinTemperature { get; set; }
        public double MaxTemperature { get; set; }
        public double WindSpeed { get; set; }
        public System.DateTime ValidDate { get; set; }
        public int LiquidAmount { get; set; }
        public double AveragePressure { get; set; }
        public double AverageHumidity { get; set; }
        public int AverageCloud { get; set; }
        public int MaximumUv { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual TImportedCity TImportedCity { get; set; }
    }
}
