//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherEx2.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TImportedCity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TImportedCity()
        {
            this.TUser2City = new HashSet<TUser2City>();
            this.TCurrentWeatherInfo = new HashSet<TCurrentWeatherInfo>();
            this.TForecastWeatherInfo = new HashSet<TForecastWeatherInfo>();
        }
    
        public int Id { get; set; }
        public int CityId { get; set; }
        public string CityName { get; set; }
        public string StateCode { get; set; }
        public string CountryCode { get; set; }
        public string CountryFull { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public System.DateTime LastModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUser2City> TUser2City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCurrentWeatherInfo> TCurrentWeatherInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TForecastWeatherInfo> TForecastWeatherInfo { get; set; }
    }
}
